Repository jac-uk/apply, pull requests merged in 2023-02, with the labels that each got.

#939 #936 Refresh of Vacancy Page
  src/App.vue
  src/assets/location.svg
  src/components/BackToTop.vue
  src/components/Badge.vue
  src/components/Breadcrumb.vue
  src/components/CustomHTML.vue
  src/components/Page/Timeline.vue
  src/components/Search.vue
  src/components/SidePanel.vue
  src/filters.js
  src/views/Vacancies.vue
  src/views/Vacancy/VacancyDetails.vue
Labels: Passed UT

#974 #953 Additional personal details fields - tooltip
  src/views/Apply/AccountProfile/PersonalDetails.vue
  src/views/Apply/CharacterChecks/PersonalInformation.vue
  src/views/Apply/CharacterChecks/Review.vue
  src/views/Apply/FinalCheck/PersonalDetails.vue
Labels: Passed UT

#967 #961 Enable candidates to apply for a vacancy in Welsh
  src/App.vue
  src/assets/welsh.json
  src/components/Breadcrumb.vue
  src/components/Form/FileUpload.vue
  src/components/Form/Form.vue
  src/components/Page/LawRelatedTasks.vue
  src/filters.js
  src/helpers/constants.js
  src/helpers/language.js
  src/router.js
  src/store/application.js
  src/store/vacancy.js
  src/views/Apply/Apply.vue
  src/views/Apply/ApplyMixIn.js
  src/views/Apply/FinalCheck/Review.vue
  src/views/Apply/TaskList.vue
  src/views/Vacancy/VacancyDetails.vue
Labels: Passed UT, Needs UT

#976 tel accepts spaces and scrollto error
  package-lock.json
  src/components/Form/Form.vue
  src/components/Form/FormField.vue
Labels: Passed UT

#979 Bugfix: #1902 Vacancy Refresh - Fee Paid Tag
  src/views/Vacancies.vue
  src/views/Vacancy/VacancyDetails.vue
Labels: Needs UT

#980 Admin#1757 Duplicate Applications - IP Address Sweep
  src/helpers/browser.js
  src/store/application.js
  src/views/Apply/Apply.vue
Labels: Passed UT, Needs UT
